image: Visual Studio 2015

platform: Any CPU
configuration: Release

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

branches:
  except:
    - gh-pages

install:
# Ensure downloads folder exists.
  - cmd: if not exist "c:\downloads" mkdir "c:\downloads"

# We need to update the dotnet environment as we use the new csproj format.
  - cmd: if not exist "c:\downloads\dotnet.exe" appveyor DownloadFile https://go.microsoft.com/fwlink/?linkid=838401 -FileName "c:\downloads\dotnet.exe" # dotnet-dev-win-x64.1.0.0-preview4-004233.exe 
  - cmd: call c:\downloads\dotnet.exe /quiet

# The current versions of OpenCover do not support the new PDB format - download a pre-release version which does.
  - cmd: if not exist "c:\downloads\OpenCover.zip" appveyor DownloadFile https://ci.appveyor.com/api/buildjobs/xj78v6dac42uob8q/artifacts/main/bin/zip/opencover.4.6.589.zip -FileName "c:\downloads\OpenCover.zip" # OpenCover 4.6.589.zip
  - cmd: 7z x c:\downloads\OpenCover.zip -oc:\OpenCover\

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - ps: dotnet --info
  # We currently have to use msbuild /m:1 rather than dotnet build - see https://github.com/dotnet/cli/issues/4786
  #- ps: dotnet build -c $ENV:CONFIGURATION
  - ps: dotnet msbuild /m:1 /p:Configuration=$ENV:CONFIGURATION

test_script: 
  - ps: .\build\scripts\run-tests.ps1
  - cmd: "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - cmd: pip install codecov
  - cmd: codecov -f "%APPVEYOR_BUILD_FOLDER%\opencoverCoverage.xml"

after_build:
  - ps: .\build\scripts\create-packages.ps1

artifacts:
  - path: 'artifacts\packages\*.nupkg'

cache:
  - c:\downloads\dotnet.exe -> appveyor.yml
  - c:\downloads\OpenCover.zip -> appveyor.yml
  - '%USERPROFILE%\.nuget\packages -> *.csproj, appveyor.yml'