version: 3.4.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

branches:
  except:
    - gh-pages

before_build:
- cmd: nuget restore GravatarHelper.sln

image: Visual Studio 2015

platform: Any CPU
configuration: Release

build:
  parallel: true  
  project: GravatarHelper.sln
  verbosity: minimal

after_build:
- nuget pack NuGet\GravatarHelper.nuspec -Version %APPVEYOR_BUILD_VERSION%
- 7z a GravatarHelper-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\GravatarHelper\bin\%CONFIGURATION%\*.dll

artifacts:
- path: GravatarHelper-$(APPVEYOR_BUILD_VERSION).zip
- path: GravatarHelper.$(APPVEYOR_BUILD_VERSION).nupkg
